# Generated by Django 5.2.5 on 2026-08-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
    ]
