# Generated by Django 5.2.5 on 2026-08-11 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quisetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('page_number', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('quition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemreq.quisetion')),
            ],
        ),
        migrations.CreateModel(
            name='Servey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='quisetion',
            name='servey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemreq.servey'),
        ),
        migrations.CreateModel(
            name='UserServey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(default=0.0)),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('servey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemreq.servey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'servey')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('answer_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemreq.answeroption')),
                ('quition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systemreq.quisetion')),
                ('user_servey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='systemreq.userservey')),
            ],
            options={
                'unique_together': {('user_servey', 'quition')},
            },
        ),
    ]
